spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.tkhvnxzvkcsxuovhqdsj&password=IniPasswordBuatTugasAdpro
spring.datasource.username=postgres.tkhvnxzvkcsxuovhqdsj
spring.datasource.password=IniPasswordBuatTugasAdpro

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public
spring.flyway.schemas=public

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
